version: '3'

services:
  app-bicicletario:
    image: adminer
    restart: always
    ports:
      - 11001:8080
    depends_on:
      - db-bicicletario

  db-bicicletario:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bicicletario
    ports:
      - "11000:5432"
    
    volumes:
      - ./db:/var/lib/data
